---
name: Build, Scan and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "application/**"
      - "!application/README.md"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GitLeaks scan
        uses: zricethezav/gitleaks-action@v2

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Build Docker image
        run: |
          docker build -t sreevasmk1993/employees-data-app:${{ github.sha }} ./application

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
          sudo mv ./bin/trivy /usr/local/bin/trivy
          trivy --version

      - name: Scan Docker image with Trivy
        run: |
          trivy image \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            sreevasmk1993/employees-data-app:${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag sreevasmk1993/employees-data-app:${{ github.sha }} sreevasmk1993/employees-data-app:latest
          docker push sreevasmk1993/employees-data-app:${{ github.sha }}
          docker push sreevasmk1993/employees-data-app:latest

      - name: Clone Helm repo for EKS (prod)
        run: |
          git clone https://x-access-token:${{ secrets.EKS_HELM_TOKEN }}@github.com/Sreevas-MK/employees-data-app-eks-helm.git helm-prod

      - name: Update Helm values.yaml (prod)
        run: |
          cd helm-prod
          yq eval ".flask.image.tag = \"${{ github.sha }}\"" -i values.yaml
          git config user.name "Sreevas-MK"
          git config user.email "sreevasmk@gmail.com"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main

      - name: Clone Helm repo for Dev
        run: |
          git clone https://x-access-token:${{ secrets.DEV_HELM_TOKEN }}@github.com/Sreevas-MK/employees-data-app-helm-dev-infra.git helm-dev

      - name: Update Helm values.yaml (dev)
        run: |
          cd helm-dev
          yq eval ".flask.image.tag = \"${{ github.sha }}\"" -i values.yaml
          git config user.name "Sreevas-MK"
          git config user.email "sreevasmk@gmail.com"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main

